name: unit-test

on:
  workflow_dispatch: 
  pull_request: 
    branches: ['**']

env:
  GO_VERSION: 1.21.x

jobs:
  unit-test:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
    - uses: actions/checkout@v2
    - uses: actions@setup-go@v2.1.3
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: test unit
      run: cd todo && go test -v ./